### ISSUE TITLE
Extension of the code to Johnson-Cousins UBVRI filter

### ISSUE THREAD

**Issue by neuronphysics** [gillenbrown/rsz#1]
Hi,

I came across your code for measuring the redshift of galaxy cluster with red sequence, I am wondering whether your code is applicable for Johnson-Cousins UBVRI filter or not? 

Thanks

**Comment by gillenbrown** [comment]
In principle, definitely. The process should work just fine, as long as the filters span the 4000 angstrom break in the rest frame of the clusters you are observing. 

In practice, the code isn't currently set up to handle this filter set, but would only take some minor modifications to get it up and running.

**Comment by neuronphysics** [comment]
I added my filter set to ezgal filter file and then I installed ezgal but it seems my filters are not normalized compatible with ezgal format and it returns 'NaN' values. I don't know how I can fix the problem. I will appreciate if you give a tip. Is it the only place I have to include the filters?

Another question, is there any specific reason that you give a fixed value for slope and one for intersect of linear fitting in 'model.py' to the code?
Thanks again.

**Comment by gillenbrown** [comment]
I'm pretty sure ezgal already has the UBVRI filters, so you shouldn't need to add your own. That said, the ezgal filters are actual transmissions (including sky, atmosphere, mirror, etc), so they shouldn't be normalized to one. Take a look at the filters included with ezgal to see the format it takes, too. The ezgal/data/filters/ directory is the only place you need to include the actual filter files. 

Which fit and intercept are you talking about? There are a couple in that file.

As a side note, I am going to make the code more compact in the near future. I will also add a guide on how to add new filter combinations. If you can wait, it might be easier to add your stuff once my code is in better shape in that regard.

**Comment by neuronphysics** [comment]
Well, as you mentioned I checked ezgal/data/filters/ directory and the UBVRI are not included.  Take a look here:
http://www.baryons.org/ezgal/filters.php
In RSModel class and 'slope' method of _Slope class there are two lists of "fits" params.

To be honest I need to see whether I can make your code work for my application as soon as possible, because I need the results as a cross check.

**Comment by gillenbrown** [comment]
Huh. I have filter files named just u, b, v, r, i, and they are listed [here](https://github.com/dpgettings/ezgal/tree/master/ezgal/data/filters) as well. You could download those.

The fit in the RS model class is am empirical correction I used to calibrate the method. The results without it are close, but not that great. This fixes that problem.

The _Slope class describes the slope of the red sequence. The slope of the cluster red sequence has been measured in many filters, so I can find the red sequence slope at any redshift based on what filters we are observing in the rest frame. I don't let it vary because the real red sequence slope does not vary. The intercept is based on the output of ezgal.

How good do the results need to be? I don't trust the results produced by this code to anything within about 0.1. You also need a training set of clusters with known redshift to calibrate the correction. Otherwise the results aren't that reliable.

**Comment by neuronphysics** [comment]
Hi Gillen,

Well, I have photometric redshifts. I just want to use this code and its results as a  cross check, plus use it to determine the red-sequence cluster members and possibly the BCGs of my clusters (I would appreciate if you comment on this whether it is a good approach or not). But at the moment after two days that I have tried to change your code, it doesn't return any output and I don't know why?!! :P
 My clusters are in low redshifts. I am wondering whether your code is able to work for low redshift clusters or not?

**Comment by gillenbrown** [comment]
My code would definitely be a good way to find the red sequence members, but finding the BCG may not be as reliable. 

How low is low redshift? z~0.5 is probably around the limit.

**Comment by neuronphysics** [comment]
My clusters are between z~0.13 to 0.4.. What is the reason that you reckon it might not work for low redshift galaxy clusters?

**Comment by gillenbrown** [comment]
The bands you use need to span the 4000A break in the observed frame. The models also need to be monotonic in color and magnitude as a function of redshift, and at lower redshift this may not be the case.

**Comment by neuronphysics** [comment]
I guess my filters cover the redshift range of clusters even in rest frame(UBVRI). I found a bug in cluster.py script. I guess you need to pass 'params' as an input to the '_location_cut' method of the ''Cluster" class. 
You also mentioned in the code what method would people suggest to get the slope of the fitted line? What do you think of linear fit methods by python libraries? Couldn't they be used in this case and if not, why?

**Comment by gillenbrown** [comment]
You shouldn't need to pass in params to _location_cut(). There shouldn't be that many things you need to change to get the code to work. Have you successfully ran the example with rsz_irac? That would be a good first step before we change the code.

The slope of the red sequence is determined by by interpolating between the measurements of the red sequence slope in different bands, based on what rest frame filters are seen at that redshift.
I would not do linear fitting. We make models of where the red sequence will be if the cluster is at different redshifts (where each model has a certain slope and M\* point), then pick the best one. The slope and intercept aren't independent. Those methods also won't correlate a redshift with the line of best fit like my code does. 

You could just set the red sequence slope to zero. It's wrong, but isn't that wrong. It will give you answers that are in the ballpark, at least.

**Comment by neuronphysics** [comment]
The code is working to the end and returning some results. In the plotted figure the red sequence galaxies are all over the field and are just around 50 points scatter in the field. I am sure there should be more galaxies belong to the red sequence close the cluster center. 

Does this weird result have anything to do with the color cuts? should I put appropriate limits for them to get more reasonable results? I apologize that I ask a lot of questions.

Thanks.

**Comment by neuronphysics** [comment]
I was able to run your example. When I run it for my cluster it doesn't return nothing similar to your example. There are couple of stuff that I am wondering about:
1. Is it a general case that you have normalized the model with the magnitude of Coma cluster in 'Ks' band or in my application I need to use another values?
2. What does 'correction' method of RS class exactly do (why did you need a polynomial fit) and how did you obtain the 'fit' list of values?
3. In the '_initial_z' method of 'Cluster' class is there any specific reason that you set the magnitude bounderies between 'mag_point-2.0<source.z_mag<mag_point'?

**Comment by gillenbrown** [comment]
If the "red sequence" galaxies are scattered all around then the red sequence isn't being fit properly. What do the CMDs look like? You may need to enable them in the param file. Can you post one here? That will help troubleshoot a lot of things.

The color cuts could be a reason. Pick ones that kind of isolate the red sequence. It's a judgement call, really.

Did you run the example with your modified code, or the original?

The Coma normalization should probably be kept. The normalization tells ezgal to produce a galaxy that matches M\* in Coma. If you want to match some other normalization you have, then you can use that, but Coma should be fine. Whatever you use, it should be the characteristic magnitude of the red sequence. 

The correction is a fudge factor that comes from the results not being perfect. It was found by comparing the results of my code with known redshifts, then figuring out the correction that mapped my results onto the spec z's. You could have it just `return z`, which would be no correction. If you have a bunch of known redshift, you could figure out what the correction should be.

That's where the red sequence signal is strongest (and by that I mean that there are many galaxies dimmer than the `mag_point`, but the ones that are brighter are likely to be RS members). Like the color cuts, it's a judgement call on what to choose for those values.

**Comment by neuronphysics** [comment]
![a226_rs](https://cloud.githubusercontent.com/assets/6558617/9766603/118683f0-571a-11e5-8255-8ae8e2c07134.png)

These plots are the CMD of galaxies in 1.5 arcmin of the cluster center as a function of distance from the assumed center and photo-zs (The plot is not the out put of your code though :P).  I have changed the name of variables, filters for model of 'ezgal' but for setting the magnitude and color cuts I am a bit confused because I don't know from where I should start.  
BTW, I ran the unmodified version of your code and the results look very promising for your data.

**Comment by gillenbrown** [comment]
I'm glad the code works on the example. If it works, can you post the CMD output by my code? I'm most interested in seeing the overplotted red sequences. Once we get it up and running the code should work well on the example you posted. 

Here is a list of things you should change. I'm not sure it's comprehensive, but it's a start. You could rename the variables for color and magnitude if you want, but it's not necessary. It might be easiest to _not_ rename them, actually. It's a lot of work and it's easy to mess up.
- rsz_irac (the executable file): it should work, but some cosmetic changes might be nice (ie rename things in the output file, print the correct bands, etc)
- data.py - no changes
- plotting.py:
  - Should work, although the main axes of the plots will be in AB rather than Vega mags. You might need some cosmetic changes there.
- source.py - no changes, unless you want to rename the variables for color and magnitude.
- model.py:
  - class `_Slope`:
    - `__init__`
      - could change the slope returned by the function defined within if you know how to calculate it. Zero slope will be fine for now, though. just have `slope()` return 0.
  - class `RSModel`
    *`correction`
    - have it `return redshift` at the beginning before doing anything else. You may eventually want to fit a correction, but for now this will be fine.
  - `model_dict()`
    - update the lower and upper limits in `zs = np.arange(0.7, 1.700001, spacing)` so that is spans the redshift range of your clusters. Making it very wide will be good for now. The limits are actually chosen by determining where it is monotonic with redshift, but we don't know where that is yet. Make it a wide range and post the CMD my code created with red sequences overplotted.
    -  replace 'ch1' and 'ch2' with the appropriate filters in this line: `mags = model.get_apparent_mags(zf, filters=["ch1", "ch2"], zs=zs, ab=True)`. Make sure the names you put in match the filters in the `ezgal/data/filters/` directory.
- cluster.py:
  *`_name()`
  - may need to be modified to correctly parse your file names.
    - `get_mags()`:
  - If you pass in fluxes that aren't in uJy, change the zeropoint in the section that converts flux to mag.
  - add conversions from Vega to AB in the second to last chunk of code. My code works in AB under the hood.
    - `fit_z()`
  - change the color and mag cuts starting in line 257. These are probably fine to leave for now, but will need to be modified once we see the CMD with the RS members shown.
  - `_initial_z()`
    - May want to change the color and mag cuts here again, but they should be fine where they are for the moment.

I think that's everything! Hopefully this helps.

**Comment by neuronphysics** [comment]
![output-0](https://cloud.githubusercontent.com/assets/6558617/9771473/bd377c7e-5736-11e5-9f53-ce9a54600d80.png)
![output-1](https://cloud.githubusercontent.com/assets/6558617/9771475/c12436f6-5736-11e5-92fa-14c85e96ea77.png)
![output-2](https://cloud.githubusercontent.com/assets/6558617/9771476/c41c4934-5736-11e5-8768-fc65b5c9ef5c.png)
![output-3](https://cloud.githubusercontent.com/assets/6558617/9771481/c8590032-5736-11e5-95f1-bacd2394aa00.png)
![output-4](https://cloud.githubusercontent.com/assets/6558617/9771484/cbdb0a8e-5736-11e5-9b0a-3d7f3def2ac1.png)

I have done all the changes you have mentioned and I got the upper plots. There is something really fishy going on, because my cluster should have z~0.2. Although the center I choose might not be the real cluster center but I am sure it covers a considerable part of the cluster. I don't quite understand why does code pick RS memebers totally off from the region close to the given cluster center and I am pretty sure something is really wrong because I should have more RSs.

**Comment by gillenbrown** [comment]
Your cluster center is probably not the problem. It looks like something is wrong with the conversion from AB to Vega. The red sequence predictions are not close to your cluster data as they should be. Something is definitely off there. That needs to be fixed first before anything else will work properly. An easier option might be to have ezgal output mags in Vega rather than AB. Then you wouldn't need to mess with the conversion stuff.

Also, it looks like a slope of around -0.1 would be better as the slope of the red sequence, rather than 0. Minor thing, but it will help improve things a little once they work. 

The code applies the cut that selects RS members to the whole field, not just inside the location cut. This was done to allow for all the possible RS members to be identified, even if a very small radius was used.

**Comment by gillenbrown** [comment]
As a quick check, here's what I'm getting for the V-I vs I RS points in Vega mags. It looks like something is off between my plot here and the one you posted above.

![image](https://cloud.githubusercontent.com/assets/12191474/9772079/ac06ec8c-56ff-11e5-996a-c3d2d46e8b37.png)

**Comment by neuronphysics** [comment]
can I have an email from you to send my filters to you to add to ezgal filter file?

**Comment by gillenbrown** [comment]
gbbtz7@mail.umkc.edu

I think I already have V and I filter files somehow, but I will try with yours.

**Comment by neuronphysics** [comment]
Don't you think in my data according to the CMD even there are two lines of red sequences? BTW, did you try the filters that I sent you?

Thanks again.

**Comment by gillenbrown** [comment]
There is definitely a red sequence around a color of 2.0. It looks like there might be one around 1.3, but I suspect those are probably foregrounds or just nearby blue objects. I suspect most of them would go away if you did a smaller location cut. 

I did use your filters, and got the same results you did. 

It looks like the colors of our red sequences aren't too far off, but the magnitudes definitely are too bright. We could change the normalization of the ezgal model. It's normalized to match Coma now, as you know, but we could change it. Do you have a value for the typical characteristic magnitude of your cluster sample? We could use that instead. The big offset from Coma worries me a little, but we could try.

**Comment by neuronphysics** [comment]
I also used the recipe you have given in https://github.com/gillenbrown/rsz/blob/master/rsz_rz/rs_slope/RS_slopes.ipynb to estimate the slope of the line and I think it looks slightly better but the previous results didn't change.
I guess there are two large scale structures because I also get two peaks in the weak lensing signal-to-noise map and I want to infer it with red sequence as well. One should be around z~0.12 and the other at z~0.29.

**Comment by gillenbrown** [comment]
Oh, great. The slopes will only matter once we fix the problem of the models not lining up with your data. Have you tried changing the normalization?

That is really interesting. It looks like the main one I saw is the one at 0.12.
